services:
  db:
    image: postgres:16-alpine
    container_name: my-facebook-db
    environment:
      POSTGRES_DB: myfacebook
      POSTGRES_USER: myfacebook
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
